services:
  app:
    build:
      context: .
      args:
        LOCAL_UID: ${LOCAL_UID:-1000}
        LOCAL_GID: ${LOCAL_GID:-1000}
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PHX_SERVER: "true"
    command: ["bash"]
